### ISSUE TITLE
add version check?

### ISSUE THREAD

**Issue by davidcarlisle** [latex3/iftex#1]
`ifetex.sty` (but not `ifetex.tex`) has an optional version check

```
\newcommand*\NeedsETeX[1][]{%
  \ifetex
    \ifx\@nnil#1\@nnil\else
    \ifdim\the\eTeXversion\eTeXrevision\p@<#1\p@\relax
```

This could of course be kept in an ifetex.sty stub (assuming that Martin would agree to a stub) but it would be possible to have the stub package just do `\let\NeedsETeX=\RequireeTeX`  and have all the `iftex`    `\Require...` commands have an optional version argument if used with latex.

**Comment by josephwright** [comment]
`\NeedsETeX` is used once in TeX Live 2019 by `typeface.sty`, and there the optional argument is unused: I really doubt anyone is testing v1/v2 for e-TeX.

**Comment by davidcarlisle** [comment]
oh sure but I meant should we add a version check for all of them so

`\RequireLuatex[1.10]`

for example.

**Comment by davidcarlisle** [comment]
I decided not to do this for now, made the \NeeedsETeX emulation ignore its optional argument and didn't add an argument to \Require...TeX commands.
