### ISSUE TITLE
Some macros undefined when using dtxgen

### ISSUE THREAD

**Issue by ServusCarolus** [latex3/iftex#10]
Thanks for your great work! I am currently updating my `nameauth` package, switching to `iftex` from the older packages, and I discovered that the `\tutex` and `\TUTex` macros are undefined when using `dtxgen`, but work normally in normal documents. Steps to reproduce are as follows:

    dtxgen mwe.sty
    <edit mwe.dtx>
        add \usepackage{iftex} below \usepackage{\jobname}
        add \meaning\tutex and \meaning\TUTeX
    make

When one views the PDF output, the result shows `\undefined` twice. When using a regular document, the results are either `\iffalse` or `\iftrue`. I attached a ZIP file with the makefile and DTX file therein.

[mwe.zip](https://github.com/latex3/iftex/files/4047034/mwe.zip)

I use both the distro version of TeXLive in Mint 19.3 and the current vanilla TL. I switch between the two using the script I created:

https://github.com/ServusCarolus/tl-switch

Thanks again!
Charles P. Schaum

**Comment by davidcarlisle** [comment]
a makefile (using shell-escape:( ) and 3rd party bash script dtxgen isn't really a reasonable test file for a cross platform system that doesn't assume make or bash is available,  but I tried to follow the instructions as far as possible. however the meaning of the commands was shown as \iffalse not undefined in the mwe.pdf I generated.

Presumably if you make and edit mwe.dtx as you describe then just that file and `pdflatex mwe.dtx` should be enough to show the problem?

If so please submit such a dtx, and the log file you get from that run.

Are you sure you are using the iftex.sty from this repository, not the original version (which does not define \iftutex)

**Comment by davidcarlisle** [comment]
oh correction it seems to be simply a typo in your test

>   I discovered that the \tutex and \TUTex macros are undefined 

Those commands are not intended to be defined, you presumably intended to test for `\iftutex not \tutex.

**Comment by ServusCarolus** [comment]
Sorry for the typos! Thank you so much for dealing with my brain lapse and helping me to find the root cause! I will switch to a more cross-platform means to create the package files. EDITED: It is no longer a `dtxgen` issue, but the result of old config files where I did not expect them. The error does not occur in the body text, but only within the driver guards of the  DTX file (after fixing the typos):

    %<*driver>
    \documentclass{ltxdoc}
    \usepackage[a4paper,margin=25mm,left=50mm,nohead]{geometry}
    \usepackage[numbered]{hypdoc}
    \usepackage{\jobname}
    \usepackage{iftex}
    \iftutex THIS WILL FAIL \fi

    \EnableCrossrefs
    \CodelineIndex
    \RecordChanges
    \begin{document}
      \DocInput{\jobname.dtx}
    \end{document}
    %</driver>

That gives the undefined control sequence error. Yet in the driver section of the DTX file, using `\newif` and some cases of testing conditionals can produce undocumented behavior. This is now fixed by cleaning out the old config.

**Comment by davidcarlisle** [comment]
It is still not clear how to test this, the code fragment in the previous  comment is not intended to be a complete dtx file is it? do you have a dtx file that shows the problem?

If `\usepackage{iftex}` can not be executed inside the scope of an `\iftrue` then that would be a bug, which is why I'm asking if you can supply such a thing, but  any usage such as

```
\iffalse
\usepackage{iftex}
\iftutex THIS WILL FAIL \fi
\fi
```

will fail on general principles unrelated to the iftex package as the package will not load (due to the iffalse) so the `\iffalse` ends at the first `\fi` leaving the second `\fi` as an unmatched `\fi` and a tex error.

**Comment by ServusCarolus** [comment]
I later found that there was a stale config file lurking about that pointed to the wrong TL distribution, which caused the problem. I fixed it and it's all good. Just slap me stupid. And `dtxgen` is exculpated as well.
