### ISSUE TITLE
\ifluatex is undefined

### ISSUE THREAD

**Issue by FranzAtGithub** [latex3/iftex#14]
Hi,
I could swear it worked before, but today the MWE below produced the error: `Undefined control sequence. \ifluatex`

```tex
\documentclass{article}

% \usepackage{ifluatex}
\usepackage{iftex}

\begin{document}
Hello
\ifluatex%
    LUA
\else
    noLUA
\fi
\end{document}
```
If I change the two packages it works fine again. What could be the problem?

[mwe_ifluatex.log](https://github.com/latex3/iftex/files/4756885/mwe_ifluatex.log)

**Comment by u-fischer** [comment]
You are using an old tex: TeX Live 2017/Debian. There iftex doesn't contain ifluatex yet.

**Comment by FranzAtGithub** [comment]
Ah ok, ty! Though I feel like it worked previously on the same installation. Anyway, I will update my Tex Live Version.
