### ISSUE TITLE
Worked fine in xubuntu 18.04, broken in 20.04

### ISSUE THREAD

**Issue by henriElana** [latex3/iftex#15]
This problem arises with the sesamanuel package : https://www.ctan.org/pkg/sesamanuel.
No compilation problems in xubuntu 18.04 with texmaker.
in xubuntu 20.04, systematic **ifvtex.sty** error :
! Incomplete \ifx; all text was ignored after line 243....
Same problem in texstudio. On several computers.
The sesamanuel package is rather obscure, but this issue (https://github.com/latex3/iftex/issues/12) suggests a possible link to the Tikz package... Could be more problematic...
Either way, I have no clue. Leaving now to mourn 100+ pages of math courses, henceforth frozen in PDF.

**Comment by josephwright** [comment]
Can you provide a small example?

**Comment by u-fischer** [comment]
Please add a minimal example demonstrating the error along with a log file. As it is it quite impossible to test your issue and to check if it is still present in a current version  of the package(s).

**Comment by henriElana** [comment]
Here's an exemple, that I just tested on Xubuntu 18.04. No problem whatsoever, and the aforementioned error on 20.04.
[test latex xubuntu 20_04.zip](https://github.com/latex3/iftex/files/5130323/test.latex.xubuntu.20_04.zip)

**Comment by u-fischer** [comment]
Your iftex version is outdated: 

     Package: iftex 2019/11/07 v1.0c TeX engine tests

Current is 
 
    Package: iftex 2020/03/06 v1.0d TeX engine test

and with it your document compiles fine. 
Get a newer version from CTAN, or here from the github.

**Comment by henriElana** [comment]
Thanks a lot. It worked. You saved my day.
Wonder why the Xubuntu repository contains obsolete/broken packages.
I did try sudo apt-get update...
One more trick to try when things go pear-shaped.
