### ISSUE TITLE
\ifpdf and xetex

### ISSUE THREAD

**Issue by kberry** [latex3/iftex#16]
\ifpdf is false when running under xetex. the reason is clear, but it still seems highly inconvenient. In practice, if I want to test "is pdf being output", i would normally want to include xetex, e.g., to test what graphics format to use.

although \ifpdf surely cannot change its meaning now, how about another conditional, say, \ifpdfisoutput, which is ifpdf + xetex? i looked through the doc and the source but didn't see this. which seems like a test that documents would commonly need. wdyt? thanks.

**Comment by u-fischer** [comment]
The direct output of xetex is `xdv` which is clearly not pdf. 
Also the graphics format xetex can use are more or less the same as with latex+dvipdfmx, and you wouldn't expect this workflow to give true for your new conditional wouldn't you? Wouldn't it be safer to look into `\Gin@extensions` if you want to check if a graphics format is supported?

**Comment by davidcarlisle** [comment]
I'm not sure I understand when you want this to be true, pdf is almost always the eventual result, xetex/xdvipdfmx isn't much different to tex/dvipdfmx or even tex/dvips/pstopdf do you want this to be true in all these cases?

**Comment by Reissner** [comment]
I agree with kberry: there are usecases where I want to know the final output which is either PDF or some variant of DVI, i.e. DVI or XDV. 
This can be PDF also for xelatex. 
There are also cases where I want to know the pipeline. This is always via DVI, i.e. XDV for xelatex. 
So what we need are two macros one of which is already implemented: \ifpdf refers to the pipeline, 
and I would appreciate a command \ifpdfoutput. For pdflatex and lualatex these have the same output, 
whereas for xelatex the second shall indicate whether option --no-pdf is not set.

**Comment by u-fischer** [comment]
@Reissner 
> there are usecases
> [...]
> whether option --no-pdf is not set

Sorry but this is much to vage. Where is the use case that you want to distinguish between `xelatex file` and  `xelatex --no-pdf file` (with or without a following `xdvipdfmx file`)? 

(not that we could check that anyway -- I don't think that the command line options can be retrieved during the compilation)

**Comment by davidcarlisle** [comment]
This came up also on stackexchange the other day

https://tex.stackexchange.com/a/702457/1090

xetex runs xdvipdfmx at the end, but it is no different from using a script that runs latex then dvipdfm or latex then dvips then pstopdf, in all cases pdf is the final output but you need to insert driver specials not pdf literals.

I  don't think xetex exposes whether --no-pdf has been used but even if it did I think any if... that was true for xetex+xdvipdfmx  would need to be true for latex+dvipdfm so I propose to close with no change, sorry.

**Comment by kberry** [comment]
xetex runs xdvipdfmx at the end, but it is no different from using a
    script that runs latex then dvipdfm or latex then dvips then pstopdf, 

I beg to differ. With XeTeX, meaningful output is always PDF. Unlike
DVI, XDV serves no (non-debugging) purpose except to be converted to
PDF.  Hence my suggestion of a new conditional that is, in effect, the
current \ifpdf+xetex.

I was not aiming at specials, which can't be handled this way, as you've
pointed out, but at choice of graphics formats. With XeTeX, one needs to
include jpg|png, not eps. Hence \ifpdf is not sufficient to determine that.

But whatever, life goes on. Fine to keep it closed with no change as far
as I'm concerned.  It was just a small idea. --best, karl.

**Comment by u-fischer** [comment]
> I was not aiming at specials, which can't be handled this way, as you've pointed out, but at choice of graphics formats. With XeTeX, one needs to include jpg|png, not eps. Hence \ifpdf is not sufficient to determine that.

No it isn't sufficient. But an extended ifpdf-test isn't a solution. xetex can't handle jpg|png because it produces pdf. hint does support jpg/png too but it is clearly not outputting pdf. xetex can handle it because it is xetex --- an engine which is able to get the size of such images.

If you don't want to bother about which graphic format the engine supports then the best is to provide eps + pdf + jpg/png and then let the graphic driver do its job and to chose the preferred one ;-).
