### ISSUE TITLE
Macro to print engine logo/name

### ISSUE THREAD

**Issue by wyattscarpenter** [latex3/iftex#18]
Thanks for this useful package! I'm wondering if you could include in this package a macro that would automatically print the \LaTeX-command-style logo of the engine, like \XeTeX, or the name (presumably including \TeX) if there is no such logo. I doubt this would be much more work than a long series of `\ifxetex\XeTeX\fi`-type lines, using the tests of this package, so I think this package would be a good home for it.

My reason for wanting this is to print out the engine in the final document, for debugging and colophon purposes.

**Comment by davidcarlisle** [comment]
I can see the use case, but I don't think it fits here, it could perhaps be added to hologo or similar package?

That said, the equivalent tests in expl3 do provide a (lowercase) string:

```
\documentclass{article}

\ExplSyntaxOn
\let\enginename\c_sys_engine_str
\ExplSyntaxOff
\begin{document}

This is \enginename.

\end{document}
```

![image](https://user-images.githubusercontent.com/1268738/207559322-f2459131-31cb-428b-973b-b46c3c3dfef3.png)

**Comment by wyattscarpenter** [comment]
Interesting, I'll look into those. Thanks!
