### ISSUE TITLE
Wishlist: `\iffontspec`

### ISSUE THREAD

**Issue by callegar** [latex3/iftex#19]
Hi, may I suggest adding a test for engines that support `fontspec`?

This would be very useful with `texmaths`, a Libreoffice extension for typing (good) math using LaTeX rather the default math editor. The `texmaths` extension supports 3 engines (plain latex, xelatex and recently lualatex). Because the engine is not stored with the LibO document, the `LaTeX` preamble that you store with the document must be made compatible with all the three engines, with requires some conditionals.  Something that you typically may want is knowing if you can load fontspec and OTF math fonts (for better consistency with the LibO document) or if you need to fall back to the traditional font mechanism.
A frequent issue in LibO documents using `texmath` is that they load `iftex` in the preamble, but then only test for `xelatex`, because it is not easy to both test for `xelatex` and `lualatex`, with the result that users selecting `luatex` as the `texmath` engine get the font fallback.

**Comment by u-fischer** [comment]
> because it is not easy to both test for xelatex and lualatex

there is the `\iftutex` test, see the documentation of `iftex`.

**Comment by callegar** [comment]
Thanks and sorry for the noise, I overlooked it. To my (unsustainable) defense, I thought that \iftutex was about unicode support by the engine.

**Comment by Rimole** [comment]
@callegar So, can this issue be closed than?
