### ISSUE TITLE
LuaHBTeX

### ISSUE THREAD

**Issue by zauguin** [latex3/iftex#2]
I don't think that `\ifluahbtex` is the right test for normal usage. It does tell you if you can use `luahbtex`, but in most cases this shouldn't be important: The important question is if you can use `luaharfbuzz`. Why would it matter if you can use it because it is build into the engine or because it is available as an external library? Why shouldn't this be true for some future fork of LuaHBTeX? So I would prefer a test which is true iff `require'luaharfbuzz'` succeeds (or maybe if `luaharfbuzz` is defined, but I prefer the `require` variant because it's more flexible).

**Comment by davidcarlisle** [comment]
@zauguin  yes, you are probably right ...

the note about forks is true in general of course but mostly forks have maintained the old names and added new ones, so ptex is a fork of etex and  uptex is a fork of ptex and the tests here for uptex make the tests for etex, ptex and uptex all true.

For a fork of luahbtex it would be a matter of how radical the fork was whether you wanted the existing `\ifluahbtex`  to be true or false on the fork....


Coming back to `\ifluahbtex`  does `require("luaharfbuzz")` affect the behaviour of luatex (if you don't explicitly use `harf` mode?  That is, can I do the test without changing the behaviour?  Obviously just testing if `luaharfbuzz` is defined doesn't define anything but as you say it may not be such a good test.

**Comment by zauguin** [comment]
No, `require'luaharfbuzz'` loads the `luaharfbuzz` binary if it is available, but as long as you don't use it it doesn't have any effect (except for slightly higher memory consumption). You could call Lua's searchers yourself, but that would be more complicated and introduce edge-cases. Also in the foreseeable future `luaotfload` will do `require'luaharfbuzz'` anyway, so if you call it again it will just return the already loaded instance.

**Comment by davidcarlisle** [comment]
@zauguin  OK so something like

```
\directlua{
if pcall(require, 'luaharfbuzz') then print("NO") else print("YES") end
}
```

**Comment by zauguin** [comment]
@davidcarlisle I would switch YES and NO but otherwise yes.
