### ISSUE TITLE
Loading in INI mode

### ISSUE THREAD

**Issue by zr-tex8r** [latex3/iftex#4]
This code uses `^^J` notation, so the catcode of `^` should be set in advance.

```tex
\catcode94=7
```

I am concerned also that `\Require**TeX` macros are not `\protected` on LuaTeX in INI mode (because `\protected` is not activated in INI mode just as `\detokeinze`).

**Comment by davidcarlisle** [comment]
@zr-tex8r oops! thanks for that I'll fix.
